name: 02 DB Build

on:
  workflow_dispatch:

jobs:
  db-build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run DB scripts
        run: |
          for f in ./db/*.sql; do
            echo "Running $f"
            PGPASSWORD=test_pass psql -h localhost -U test_user -d test_db -f "$f"
          done